using F1_Garage.Models;
using F1_Models;
using Microsoft.EntityFrameworkCore;

namespace F1_Garage.Data
{
    public class ApplicationDbContext :DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        // Manufacturers
        public DbSet<Manufacturer> Manufacturers { get; set; }

        // Tyres
        public DbSet<Tyres> Tyres { get; set; }

        // ECU
        public DbSet<ECU> ECUs { get; set; }

        // Users for Login
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }

        // Shopping Cart
        public DbSet<CartItem> CartItems { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {   // Manufacturer
            modelBuilder.Entity<Manufacturer>().HasData(
                new Manufacturer { Id = 1, Name = "Pirelli", DisplayOrder = 1, Description = "Official tyre supplier for Formula 1, " +
                "providing high-performance compounds designed for speed, durability, and race strategy."},
                new Manufacturer { Id = 2, Name = "McLaren Applied", DisplayOrder = 2, Description= "Develops advanced electronic control " +
                "systems and telemetry solutions used across Formula 1 for precision performance and data analysis." },
                new Manufacturer { Id = 3, Name = "Brembo", DisplayOrder = 3, Description = "World-leading manufacturer of high-performance " +
                "braking systems, delivering reliability and extreme stopping power in Formula 1." }
                ); // Description Content generated by ChatGPT, based on general knowledge of the manufacturers' roles in Formula 1.
            
            // ECU
            modelBuilder.Entity<ECU>().HasData(
                new ECU { Id = 1, Name = "2JZ", Version = "T32", Limit = "2" },
                new ECU { Id = 2, Name = "RB26", Version = "5.6", Limit = "2" },
                new ECU { Id = 3, Name = "B58", Version = "2.2V", Limit = "2" }
                );

            // Tyres
            modelBuilder.Entity<Tyres>().HasData(
                new Tyres { Id = 1, Name = "P7 CINTURATO", Type = "Hard (DRY)", QuantityAllowed = "3" },
                new Tyres { Id = 2, Name = "PZERO E", Type = "Medium (DRY)", QuantityAllowed = "4" },
                new Tyres { Id = 3, Name = "PZERO GIALLO", Type = "Soft (DRY)", QuantityAllowed = "6" },
                new Tyres { Id = 4, Name = "PZERO CORSA", Type = "Intermediate (Treaded)", QuantityAllowed = "5" },
                new Tyres { Id = 5, Name = "SCORPION ZERO", Type = "Full Wet (Treaded)", QuantityAllowed = "2" }
                );
        }
    }
}
